// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function CreateGroup(arg1, arg2) {
  return window['go']['main']['App']['CreateGroup'](arg1, arg2);
}

export function GetMyIP() {
  return window['go']['main']['App']['GetMyIP']();
}

export function JoinGroup(arg1, arg2) {
  return window['go']['main']['App']['JoinGroup'](arg1, arg2);
}

export function LeaveGroup(arg1) {
  return window['go']['main']['App']['LeaveGroup'](arg1);
}
