// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateGroup(arg1:string,arg2:string):Promise<string>;

export function GetMyIP():Promise<string>;

export function JoinGroup(arg1:string,arg2:string):Promise<string>;

export function LeaveGroup(arg1:string):Promise<string>;
