// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function CreateGroup(arg1:string,arg2:string):Promise<string>;

export function CreateUser(arg1:string,arg2:string):Promise<string>;

export function DeleteGroup(arg1:number):Promise<string>;

export function DeleteUser(arg1:number):Promise<string>;

export function GetAllGroups():Promise<Array<database.Group>>;

export function GetAllUsers():Promise<Array<database.User>>;

export function IsServerRunning():Promise<boolean>;

export function StartServer(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function StopServer():Promise<string>;
