// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGroup(arg1, arg2) {
  return window['go']['main']['App']['CreateGroup'](arg1, arg2);
}

export function CreateUser(arg1, arg2) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function GetAllGroups() {
  return window['go']['main']['App']['GetAllGroups']();
}

export function GetAllUsers() {
  return window['go']['main']['App']['GetAllUsers']();
}

export function IsServerRunning() {
  return window['go']['main']['App']['IsServerRunning']();
}

export function StartServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartServer'](arg1, arg2, arg3);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
